version: '3.3'
networks:
  sun_network:
    driver: bridge

services:
  web:
    build:
      context: .
      
    environment:
      DB_HOST: ${DB_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      API_TOKEN: ${API_TOKEN}
    command: uvicorn sun_api:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - sun_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 88:88
    networks:
      - sun_network
