version: '3.3'
networks:
  sun_network:
    driver: bridge

services:
  web:
    build:
      context: .
    environment:
      DB_HOST: ${DB_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      API_TOKEN: ${API_TOKEN}
    command: uvicorn sun_api:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - sun_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/apisuntel.duckdns.org/fullchain.pem:/etc/nginx/ssl/cert.pem     # Монтируем cert.pem
      - /etc/letsencrypt/live/apisuntel.duckdns.org/privkey.pem:/etc/nginx/ssl/key.pem       # Монтируем key.pem
    ports:
      - "88:88"                                 # Можно заменить на "443:443", если хотите использовать стандартный порт HTTPS
    networks:
      - sun_network
